[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19"
chrono = "0.4"
anyhow = "1.0"
thiserror = "1.0"
smallvec = "1.11"
unicode-width = "0.2"
unicode-segmentation = "1.11"

[dev-dependencies]
tempfile = "3.0"